### Send POST request with body as parameters
POST http://localhost:8804/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "user",
  "password": "1111"
}

### Send POST request with body as parameters
POST http://localhost:8804/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "manager",
  "password": "1111"
}

### Send POST request with body as parameters
GET http://localhost:8804/api/messages
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Send POST request with body as parameters
GET http://localhost:8804/logout
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Send POST request with body as parameters
GET http://localhost:8804/api/admin/user
Content-Type: application/json
X-Requested-With: XMLHttpRequest

###
