server:
  port: 8804
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql:주소
    username: 아이디
    password: 비밀번호
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql:true
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true

    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernamte.type: trace
